name: Auto update events.json daily
on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: |
          node -e "
          const fs=require('fs');
          const d=new Date();
          function f(n){return String(n).padStart(2,'0')}
          const yyyy=d.getFullYear(),mm=f(d.getMonth()+1),dd=f(d.getDate());
          const sunset='18:15';
          let [h,m]=sunset.split(':').map(Number);
          h-=1; m-=20; if(m<0){m+=60;h--;} if(h<0)h+=24;
          const dinner=`${f(h)}:${f(m)}`;
          const obj={date:`${yyyy}-${mm}-${dd}`,sunset_time:sunset,dinner_time:dinner};
          fs.writeFileSync('events.json',JSON.stringify(obj,null,2));
          "
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add events.json
          git commit -m 'Auto update events.json'
          git push || true
